name: Run tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2.4.1
      with:
        node-version: 16.x

    - name: Restore cache
      uses: actions/cache@v2.1.4
      with:
        path: |
          .yarn/cache
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-

    - run: yarn install

    - run: yarn build
